[global]
developmentMode = false

[server]
headless = true
port = 8501
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#3fb950"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#21262d"
textColor = "#c9d1d9"
font = "monospace"
